### ISSUE TITLE
docstore support

### ISSUE THREAD

**Issue by 0zAND1z** [ipfs/go-ds-crdt#12] opened 2019-05-28 06:15 UTC
We could not find a sample example on how to use this package.

We plan to persist this data structure through CRDT on the IPFS:
```json
{
    "key": "value",
    "some_metadata": [
        {
            "sub_key": "sub_value",
            "sub_key": "sub_value"
        },
        {
            "sub_key": "sub_value",
            "sub_key": "sub_value"
        }
    ]
}
```

Can `go-ds-crdt` help us achieve this?

**Comment by hsanjuan** [comment] 2019-05-28 14:10
Yes, but for the moment I can only direct you to this as example: https://github.com/ipfs/ipfs-cluster/blob/master/consensus/crdt/consensus.go#L126

**Comment by 0zAND1z** [comment] 2019-05-29 04:49
Cool, we are happy to work with you on the examples & document them.

Let us know if we can do that here, @hsanjuan . Thanks.

Also, @akshitababel from India can help. She is researching on CRDTs, planning to test the waters by consuming this library in a sample go program.

**Comment by akshitababel** [comment] 2019-05-29 06:40
@hsanjuan The Datastore is stored on IPFS, right? When we are creating a new datastore we getting a `Datastore struct` but no where we are getting an IPFS hash to recognize that datastore, the same way when we store a file on IPFS we get an hash back. Why so? And even to execute Put, Delete, Get we are using the `Datastore struct` returned by `new()` but nowhere the IPFS hash is used. Can you please explain.

**Comment by hsanjuan** [comment] 2019-06-06 10:06
Hi @akshitababel , this library is an implementation of the https://godoc.org/github.com/ipfs/go-datastore `Datastore`  interface. Datastores, and this library are completely agnostic to IPFS, they are just key-value stores.

However IPFS can work as the `DAGSyncer` component that this library needs to work as a distributed database. https://github.com/hsanjuan/ipfs-lite does just that (act as a DAGSyncer).

From the user point of view, adding to this database has nothing to do with adding to IPFS (although internally something like that will happen). The IPFS hashes referencing the Merkle-DAG used by the datastore are printed in the logs.

**Comment by hsanjuan** [comment] 2020-02-18 19:51
This is a bit old so I'll close it. Re-open as needed.

**Closed by hsanjuan** 2020-02-18 19:51 UTC

**Comment by aloknerurkar** [comment] 2020-06-15 08:13
@hsanjuan This might not be the right forum to ask but the question is about the example you pointed out. (ipfs-cluster/consensus). First of all the example was perfect for our use-case! We want to build a distributed key-value store using our existing ipfs storage.

I wanted to understand why you have used the namespace wrapped datastore in ipfs-lite. 
```
ns := ds.NewKey(cfg.DatastoreNamespace)
blocksDatastore = namespace.Wrap(store, ns.ChildString(blocksNs))
```
Are there any additional blocks used by the datastore? The crdt store is already namespace, so I was hoping all the blocks added by the store will be under the same namespace.

We currently have an already running ipfs instance which we want to use as the DAGSyncer. Would it be an issue if we use the same store for regular files and the crdt KV store?

**Comment by hsanjuan** [comment] 2020-06-15 11:02
Let's see.. On the actual datastore (ie. badger), there will be:

* `/c/` -> which is the one used by go-ds-crdt.
* `/c/b` -> for blocks downloaded and stored by ipfs-lite.

Internally, go-ds-crdt uses `/c/h`, `/c/s/*`.

If blocks were not namespaced and they would have keys like `/QMXXX...` instead of `/c/b/QMXXX`.

When listing all the blocks, we would obtain not only the `/QMXXX` results, but also any other key since we would not be able to filter by prefix (`/c/b`). I don't think we ever need to list blocks though, but things are wrapped for housekeeping and for making sure the right prefixes allow querying for the right data if ever that is needed.

**Comment by aloknerurkar** [comment] 2020-06-15 15:36
Thanks for responding!

So if we use go-ds-crdt to store only key-value pairs directly, we don't need to worry about the block namespace right?

According to my understanding:
- The direct keys will be added as ```/c/...``` 
- The go-ds-crdt will use ```/c/h``` and ```/c/s/*``` internally
- We can have the default blockstore used by ipfs-lite (using the ```/blocks``` namespace) used for file-sharing and other namespaced datastores co-existing in the underlying badger-ds which are not part of the go-ds-crdt datastore

I believe this should not cause any issues. Right?

**Comment by hsanjuan** [comment] 2020-06-15 15:44
You don't need to namespace anything you add to the crdt-datastore. This happens transparently. Just `Put(mykey, value)` and `Get(mykey)` without thinking about the internal namespaces.

Do namespace the ipfs-lite datastore if it uses the same underlying datastore as go-ds-crdt. Otherwise, if the underlying datastore is different, it does not matter.

**Comment by aloknerurkar** [comment] 2020-06-15 16:04
So I have underlying badger datastore. I use that (without any namespace) for ipfs-lite for sharing files between peers. 

Then I am creating a new crdt datastore using this ipfs-lite and the same badger store to use strictly as a key-value store. I don't want the files to be replicated between peers but just the key-value pairs.

So main question is, there could be other types of keys in the underlying datastore. I want to make sure go-ds-crdt will not be affected by any other keys which are different from ```/c/*```

**Comment by hsanjuan** [comment] 2020-06-15 17:15
The problem is that, if your other keys are not namespaced, there could be prefix-clashes. And again, whatever needs to re-list blocks, will list a lot of unrelated crdt keys if blocks are not namespaced.

It is not a problem of things getting replicated when they should not (things don't get replicated based on namespace), but of the regular operations in the local node.

So my recommendation is to namespace/wrap the datastore used for ipfs-lite.

**Comment by aloknerurkar** [comment] 2020-06-15 17:35
Ohh okay understood. Thanks!

We were looking into Orbit-DB or possibly building our own. But this solution worked out way too neatly.
